version: "3.4"
services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/.env
    environment:
      DB_HOST: host.docker.internal
    # DB_PORT: 3306
    # DB_PASS: A123b456c
    # DB_NAME: mydb
    # DB_USER: root
    # PORT: 30001
    container_name: simple-fasthttp
