version: "3.4"
services:
  web:
    build: .
    ports:
      - "30001:30001"
    volumes:
      - /mnt/c/Users/hrd/sample_secret/.env: ./env
    environment:
      DB_HOST: host.docker.internal
    container_name: simple-fasthttp
